# Generated by Django 5.2 on 2025-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="other_service",
            field=models.CharField(
                blank=True,
                help_text="Please specify if you selected 'Other' as service",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="service",
            field=models.CharField(
                choices=[
                    ("web_development", "Web Development"),
                    ("mobile_app", "Mobile App Development"),
                    ("ui_ux", "UI/UX Design"),
                    ("consulting", "IT Consulting"),
                    ("maintenance", "Maintenance & Support"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
